lib/heaven/provider/default_provider.rb

Occurs during test run
```
lib/heaven/provider/default_provider.rb:150:56: W: File.exists? is deprecated in favor of File.exist?.
output.stderr = File.read(stderr_file) if File.exists?(stderr_file)
^^^^^^^
lib/heaven/provider/default_provider.rb:151:56: W: File.exists? is deprecated in favor of File.exist?.
output.stdout = File.read(stdout_file) if File.exists?(stdout_file)
^^^^^^^
```

Updates File.exists? signature to File.exist? to avoid deprecation warning

---

lib/heaven/jobs/deployment.rb

The deployment payload format changed in October. https://developer.github.com/changes/2014-10-21-deployment-webhook-payload-changes/ This uses the nested keys.
Fixes #128

Fix double deploys by locking properly

---

lib/heaven/notifier/default.rb

The user link will default to https://github.com, which isn't right for Enterprise installs.

fix notifier user link when using Github Enterprise

---

app/models/concerns/deployment_timeout.rb
app/models/concerns/local_log_file.rb
doc/providers.md
lib/heaven/provider/default_provider.rb

Adds the ability to use POSIX::Spawn timeouts to actually kill the deployment processes when hitting a timeout. It seems that the current ruby timeout leaves the processes running. The behavior is controlled with `TERMINATE_CHILD_PROCESS_ON_TIMEOUT` env. 
The processes are killed a bit before the ruby timeout hits. The 2 seconds is just something I pulled out of thin air so I'm all in for changing it to something. 
This also catches both kinds of timeouts in deployments and appends a notification to the error log that there was a timeout so this pr also kind of takes care of rest of the issues in #88.
We'll need to run this for a while ourselves to test how this actually performs, but opened this for initial thoughts.

Better handling of timeouts

---

lib/heaven/notifier/flowdock.rb

It seems that the Flowdock notifier is no longer compatible with the newest data format and crashes when trying to use nil objects. This pr fixes those issues.

Flowdock notifier to work with new payloads

---

.rubocop.yml

I took a look at the build failure and it errored out with:
```ShellSession
Offenses:
lib/heaven/notifier/default.rb:6:5: C: Class definition is too long. [142/140]
class Default
^^^^^
85 files inspected, 1 offense detected
```
I figured bumping the max class length isn't too terrible a way of dealing with this.

Bump max class length to green the build.

---

lib/heaven/provider/default_provider.rb

A deployment timeout caused a throw because of a typo.

Fix typo in deployment timeout handling

---

doc/providers.md
lib/heaven/provider.rb
lib/heaven/provider/shell.rb

A provider that just executes a file from the repository as the deployment task. This is suitable in cases when you're only deploying for example a project that's only frontend assets, so the deployment is just asset compilation and push to S3.
The provider validates that the deploy script is a file inside the repo so arbitrary commands cannot be run. The script to be run can be given in the provider configuration.

Shell provider

---

lib/heaven/provider/shell.rb

`execute_and_log` eventually forks a child that runs the `deployment_command`. Unfortunately Heaven's Bundler environment leaks to that process, so deploy scripts are not able to use their own instance of Bundler.
Running the `deployment_command` inside `Bundler.with_clean_env` should fix the issue.

Run shell provider in a clean bundler environment

---

app/services/environment_locker.rb
spec/services/environment_locker_spec.rb

Useful if you want to say "ship" instead of deploy

Support other prefixes

---

doc/notifications.md
lib/heaven/notifier/slack.rb

Allow Slack notifications to have a custom name and/or icon.

Allow Slack notification customisation

---

app/models/auto_deployment.rb

Should fixup https://github.com/atmos/heaven/issues/103, previously every environment defaulted to production.
@filipegiusti Is this what you're getting at?

Pass the correct environment parameter to api deployment creation

---

.buildpacks
app.json

Heroku has first-class support for multiple buildpacks now, so ddollar's buildpack isn't necessary anymore. This PR removes .buildpacks and adds the ruby and python buildpacks to app.json. For existing apps, you'll need to run something like:
```
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-ruby.git
heroku buildpacks:add https://github.com/heroku/heroku-buildpack-python.git
```
And possibly:
```
heroku config:unset BUILDPACK_URL
```

Use new buildpacks specification

---

doc/providers.md
lib/heaven/provider/bundler_capistrano.rb

This makes bundler_capistrano provider support all of capistrano 2.x,
3.x as well as >=3.4. The branch is passed in an environment variable
for all and this might need just a minor modification to the
deployment config. 3.4 starts to throw up when the -s arguments are
present.
See discussion in https://github.com/atmos/heaven/commit/8b2921bddf72e6bfdc6cc8ab319c5ad16523e6a2.

Remove bundler capistrano -s parameter

---

lib/heaven/provider/bundler_capistrano.rb
lib/heaven/provider/default_provider.rb

We use built-in flags for both `curl` and `tar` to ensure that the archive
files are going where we want them to.
The directory format inside the GitHub tarball is this:
`<owner/organization name>-<repository name>-<full-sha-hash>`
so we create the `unpacked_directory` in this format.
Fixes changes made in #166. Would be good if @maletor has a look too.

Make the new archive format work on Heroku

---

app.json
doc/providers.md
lib/heaven/provider/bundler_capistrano.rb

This allows us to use a *single* private bundler source without storing
the private credentials in our `Gemfile.lock`
Replaces #147

Allow private bundler sources

---

lib/heaven/notifier/flowdock.rb

We need to set X-flowdock-wait-for-message header in order to make sure we get response containing thread ID.

Fix flowdock deployment thread link in chat response

---

config/initializers/warden-github.rb

Uses a dummy placeholder instead, similarly to [api_client.rb](https://github.com/atmos/heaven/blob/v0.9.0/app/models/concerns/api_client.rb).
Closes #183

Remove default value for GITHUB_TEAM_ID

---

lib/heaven/notifier/default.rb

Slack started receiving user's ids as the username with recent changes to hubot-deploy. This makes notifiers in heaven not work as expected since they don't necessarily have an easy way to look up the user id. This introduces a new payload variable that can be set that passes through to the old behavior of the attribute is absent.
/cc https://github.com/atmos/hubot-deploy/pull/101

Display a user_name if present

---

app/models/concerns/local_log_file.rb
app/models/deployment/credentials.rb
lib/heaven/provider/default_provider.rb

This solves a problem that was happening on Heroku's cedar-14 stack.
Openssh was using the home directory from /etc/passwd instead of the
home directory from $HOME.
Closes #192 
Something to note:  I'm doing 2 things: Putting the SSH key in the actual home directory, and removing the overriding of the HOME env var.
I tried doing this without removing the HOME env var overriding behavior, but it turns out that Fabric (and the underlying paramiko ssh library) actually respects the value of the HOME environment variable when looking for the ssh config, even when SSH itself does not.  Go figure.

Put SSH private key into user's actual home dir.

---

Dockerfile

If we try to build the current version we get this error:
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Your Ruby version is 2.3.0, but your Gemfile specified 2.3.1
Updating the ruby version as suggested by the error message.

Updating Dockerfile to the 2.3.1 version of Ruby
